<a href="https://colab.research.google.com/github/AditiSatsangi/Jodhpur-Map-and-OD-Matrix-for-Multiclass-Vehicles/blob/main/Jodhpur_Map_and_OD_Matrix_for_Multiclass_Vehicles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
!pip install folium



Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [31]:
pip install folium pandas geopandas numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


**Importing** **Libraries**

In [32]:
import folium
import pandas as pd
import geopandas as gpd
import numpy as np
from folium.plugins import HeatMap
from PIL import Image
import random


Data Collection

In [33]:

jodhpur_shapefile = '/absolute/path/to/jodhpur_shapefile.shp'



Calculating OD distance

In [34]:
from geopy.distance import geodesic

def calculate_od_value(origin, destination):
    origin_lat, origin_lon = origin
    dest_lat, dest_lon = destination
    origin_point = (origin_lat, origin_lon)
    dest_point = (dest_lat, dest_lon)
    distance = geodesic(origin_point, dest_point).km
    return distance


In [35]:
# NODE POINTS
#26.266712, 73.010014 -H
#C-26.271594, 73.015733- rail - C
#26.267382, 73.019237- taj har -D
#26.273162, 73.020501- bsnl-F
#26.272427, 73.008131- A - goyalhospital- A
#122, East Rd122, East RdSardarpura, Jodhpur, Rajasthan 342003 26.275052, 73.012987-G
#26.269826, 73.007718- B
#Rajasthan 342001 26.269270, 73.018931 -E

Creating Origin and Destination Coordinates in Jodhpur City

In [36]:
# Create a list of origin and destination coordinates in Jodhpur city
# Taking Latitude and Longitudes of the node points
origins = [(26.266712, 73.010014), (26.271594, 73.015733), (26.267382, 73.019237), (26.273162, 73.020501)]  # Add the latitude and longitude of origin points
destinations = [(26.266712, 73.010014), (26.271594, 73.015733), (26.267382, 73.019237), (26.273162, 73.020501)]  # Add the latitude and longitude of destination points


Intialization of OD Matrix

In [37]:
# Create a matrix to store the OD values
od_matrix = np.zeros((len(origins), len(destinations)))


In [38]:
# Iterate over each origin and destination pair and calculate the OD values
for i, origin in enumerate(origins):
    for j, destination in enumerate(destinations):
        # Perform calculations to determine OD values
        od_value = calculate_od_value(origin, destination)  # Replace with your own calculation logic
        od_matrix[i, j] = od_value

In [39]:
pip install --upgrade folium


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


Creating Folium map of City using foilum Python library 

In [40]:
# Create a Folium map and add the OD matrix as a heatmap layer
center_lat, center_lon = np.mean(origins, axis=0)  # Calculate the center of the city using the mean of origin coordinates
m = folium.Map(location=[center_lat, center_lon], zoom_start=12)
heatmap_data = [[point[0], point[1], od_matrix[i, j]] for i, point in enumerate(origins) for j in range(len(destinations))]
folium.FeatureGroup(name='Heatmap').add_child(folium.plugins.HeatMap(heatmap_data, radius=8)).add_to(m)


Saving map obtained

In [41]:

# Save the map as an HTML file
m.save('od_map_jodhpur.html')


Downloading Map_Jodhpur

In [42]:
from google.colab import files

files.download('od_map_jodhpur.html')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Define the classes for multiclass vehicles

In [43]:
# Define the classes for multiclass vehicles
vehicle_classes = ['Car', 'Bus', 'Truck', 'Motorcycle']


 Define the latitude and longitude coordinates for origins and destinations

In [44]:
# Define the latitude and longitude coordinates for origins and destinations
origins = [
    (26.266712, 73.010014),
    (26.271594, 73.015733),
    (26.267382, 73.019237),
    (26.273162, 73.020501),
    (26.272427, 73.008131),
    (26.275052, 73.012987),
    (26.269826, 73.007718),
    (26.269270, 73.018931)
]

destinations = [
    (26.271594, 73.015733),
    (26.267382, 73.019237),
    (26.273162, 73.020501),
        (26.273162, 73.020501),
    (26.272427, 73.008131),
    (26.275052, 73.012987),
    (26.269826, 73.007718),
    (26.269270, 73.018931)
    
]


Create a matrix to store the OD values for each class

In [45]:

# Create a matrix to store the OD values for each class
od_matrix = np.zeros((len(origins), len(destinations), len(vehicle_classes)))


ORIGIN DESTINATION MATRIX FOR MULTICLASS VEHICLES

In [46]:
# Iterate over each origin and destination pair
for i, origin in enumerate(origins):
    for j, destination in enumerate(destinations):
        # Input the number of vehicles for each class from your side
        for k, vehicle_class in enumerate(vehicle_classes):
           # num_vehicles = int(input(f"Enter the number of vehicles for {vehicle_class} from origin {origin} to destination {destination}: "))
           num_vehicles = random.randint(1, 10)
           od_matrix[i, j, k] = num_vehicles

# Print the OD matrix for each class
for k, vehicle_class in enumerate(vehicle_classes):
    print(f"OD Matrix for {vehicle_class}:")
    print(od_matrix[:, :, k])
    print()


OD Matrix for Car:
[[ 3.  6.  7.  5.  5. 10.  1.  4.]
 [ 4. 10.  2.  5. 10.  3.  2.  4.]
 [ 2. 10.  9.  8.  6.  9.  6.  3.]
 [ 3.  9.  4.  1. 10. 10.  3.  1.]
 [ 2.  6. 10.  6.  3.  2.  2.  3.]
 [ 1.  2.  9.  6.  1.  6.  7.  3.]
 [10.  7. 10.  5.  6.  6.  1. 10.]
 [ 5.  9.  2.  2.  3.  7.  8.  2.]]

OD Matrix for Bus:
[[ 1.  5. 10. 10.  5.  6.  9. 10.]
 [ 7. 10.  5.  6.  1.  7. 10.  5.]
 [ 5.  9.  6.  9.  2.  3.  6.  9.]
 [ 3.  8.  8.  9.  8.  8.  2.  2.]
 [ 4.  3.  5.  2.  3. 10.  9.  9.]
 [ 5.  9.  5.  6.  8.  4.  2.  9.]
 [10.  7.  9.  9.  2.  9.  5.  8.]
 [ 9.  9.  8.  6.  9.  9.  6.  5.]]

OD Matrix for Truck:
[[ 1.  4.  7.  9. 10.  6.  9.  6.]
 [ 6. 10.  9. 10.  4.  6.  3.  1.]
 [ 2.  9.  5. 10.  7.  6.  9.  2.]
 [ 4.  2. 10.  4.  5.  7.  8.  6.]
 [ 5.  4. 10.  6.  1.  4.  8.  8.]
 [ 3.  4.  3.  8.  7.  8.  8. 10.]
 [ 2.  5.  9.  6. 10.  3.  2.  5.]
 [ 1.  2. 10. 10.  5.  9.  4.  5.]]

OD Matrix for Motorcycle:
[[10.  2.  5.  8.  7.  5.  5.  2.]
 [ 6.  8. 10.  4.  2.  1.  8.  8.]